source("calculateTfIdf.R")
source("estimateBestFeatures.R")
source("trainRfClassifier.R")
source("dataExploration.R")
source("getVariableImportance.R")
source("dataPreparation.R")
source("normaliseTfIdfDataFrames.R")
source("trainModel.R")
message("Scripts loaded.....")
data <- LoadDataJson("data.json")
message("data.json loaded...")
GetSummaryStatisticsForTargetDataColumn(data$level)
datasets <- PrepareMasterTrainingAndTestSets(data,1)
message("Data split into master training and test sets....")
train <- datasets$train
test <- datasets$test
features <- CalculateTfIdf(train$description)
message("Training baseline classifier using job descriptions....")
library(randomForest)
message("Training baseline classifier using job descriptions....")
baseline.fit <- randomForest(features, as.factor(train$level), do.trace=F)
baseline.OOB <- ExtractOOBFromCapturedTrainingOutput(capture.output(baseline.fit))
message("Baseline OOB error with default settings and no data cleaning: ", baseline.OOB)
message("Cleaning descriptions and generating new features...")
train <- ExtractJobsInEN(train)
#features <- CleanDatasetAndGenerateFeatures(train$description)
#message("Training new classifier using cleaned job descriptions....")
#fit <- randomForest(features, as.factor(train$level), do.trace=F)
#message("Estimating optimal number of features....")
#imp <- GetVariableImportance(fit)
#oob.error <- PlotOOB(features,imp, train$level)
#oob.error[order(oob.error[,2]),]
#best <- OptimiseModel(fit,features,train$level)
best <- TrainModel(train$description, train$level)
best$model
best.OOB <- ExtractOOBFromCapturedTrainingOutput(capture.output(best$model))
message("In this iteration the best model produced an OOB error of: ", best.OOB)
message("Predicting the classes of the sub test set")
#features <- CalculateTfIdf(test$descriptions)
#message("Baseline OOB: ",baseline.OOB, "\nBest OOB with model: ", best.OOB)

message("Train with job titles instead.....")
best <- TrainModel(train$title, train$level)


best$model
best.OOB <- ExtractOOBFromCapturedTrainingOutput(capture.output(best$model))
message("In this iteration the best model produced an OOB error of: ", best.OOB)
#PredictClasses(best$model, best$features, features, test$title)