source("calculateTfIdf.R")
source("estimateBestFeatures.R")
source("trainRfClassifier.R")
source("dataExploration.R")
source("getVariableImportance.R")
source("dataPreparation.R")
source("normaliseTfIdfDataFrames.R")
message("Scripts loaded.....")
data <- LoadDataJson("data.json")
message("data.json loaded...")
GetSummaryStatisticsForTargetDataColumn(data$level)
master.data.sets <- PrepareMasterTrainingAndTestSets(data,1)
message("Data split into master training and test sets....")
sub.datasets <- PrepareSubTrainingAndTestSets(master.data.sets$train)
message("Data split into sub training and test sets for exploratory analysis....")
sub.train <- sub.datasets$sub.train
sub.test <- sub.datasets$sub.test
message("The training subset has ",nrow(sub.train) , " examples")
features <- CalculateTfIdf(sub.train$description)
library(randomForest)
message("Training baseline classifier using job descriptions....")
baseline.fit <- randomForest(features, as.factor(sub.train$level), do.trace=F)
#baseline.OOB <- gsub(".*?(\\d{,2}\\.\\d{,2})\\%","\\1",tail(baseline.output, n=7)[1])
baseline.OOB <- ExtractOOBFromCapturedTrainingOutput(capture.output(baseline.fit))
message("Baseline OOB error with default settings and no data cleaning: ", baseline.OOB)
message("Cleaning descriptions and generating new features...")
features <- CleanDatasetAndGenerateFeatures(sub.train$description)
message("Training new classifier using cleaned job descriptions....")
fit <- randomForest(features, as.factor(sub.train$level), do.trace=F)
#output <- capture.output(randomForest(features, as.factor(sub.train$level), do.trace=F))
#new.OOB <- ExtractOOBFromCapturedTainingOutput(output)
#message("OOB error with default settings after data cleaning: ", new.OOB)
message("Estimating optimal number of features....")
imp <- GetVariableImportance(fit)
#oob.error <- OptimiseNumberOfFeatures(fit,features,sub.train$level)
oob.error <- PlotOOB(features,imp, sub.train$level)
oob.error[order(oob.error[,2]),]
best <- OptimiseModel(fit,features,sub.train$level)
best$model
best.OOB <- ExtractOOBFromCapturedTrainingOutput(capture.output(best$model))

message("In this iteration the best model produced an OOB error of: ", best.OOB)
message("Predicting the classes of the sub test set")
features <- CalculateTfIdf(sub.test$descriptions)
PredictClasses(best$model, best$features, features, sub.test$level)
